// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtb_soc__Syms.h"


VL_ATTR_COLD void Vtb_soc___024root__trace_init_sub__TOP__0(Vtb_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_soc___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushNamePrefix("tb_soc ");
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+283,"resetn", false,-1);
    tracep->declBit(c+138,"trap", false,-1);
    tracep->declBit(c+28,"sim_exit_req", false,-1);
    tracep->declBus(c+29,"sim_exit_code", false,-1, 31,0);
    tracep->declBus(c+1,"gpio_out", false,-1, 31,0);
    tracep->declBus(c+1,"gpio_in", false,-1, 31,0);
    tracep->declBit(c+2,"timer_done", false,-1);
    tracep->declBit(c+284,"sim_started", false,-1);
    tracep->declBus(c+285,"raw_periph_edges", false,-1, 31,0);
    tracep->declBus(c+286,"gated_periph_edges", false,-1, 31,0);
    tracep->pushNamePrefix("dut ");
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+283,"resetn", false,-1);
    tracep->declBit(c+138,"trap", false,-1);
    tracep->declBit(c+28,"sim_exit_req", false,-1);
    tracep->declBus(c+29,"sim_exit_code", false,-1, 31,0);
    tracep->declBus(c+1,"gpio_out", false,-1, 31,0);
    tracep->declBus(c+1,"gpio_in", false,-1, 31,0);
    tracep->declBit(c+2,"timer_done", false,-1);
    tracep->declBit(c+287,"clk_periph_raw", false,-1);
    tracep->declBit(c+288,"clk_periph_en", false,-1);
    tracep->declBit(c+289,"clk_periph", false,-1);
    tracep->declBit(c+139,"cpu_mem_valid", false,-1);
    tracep->declBit(c+277,"cpu_mem_ready", false,-1);
    tracep->declBus(c+140,"cpu_mem_addr", false,-1, 31,0);
    tracep->declBus(c+141,"cpu_mem_wdata", false,-1, 31,0);
    tracep->declBus(c+142,"cpu_mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+278,"cpu_mem_rdata", false,-1, 31,0);
    tracep->declBit(c+143,"is_ram", false,-1);
    tracep->declBit(c+144,"is_apb", false,-1);
    tracep->declBit(c+145,"is_sim_exit", false,-1);
    tracep->declBit(c+146,"ram_valid", false,-1);
    tracep->declBus(c+30,"ram_rdata", false,-1, 31,0);
    tracep->declBit(c+31,"ram_ready", false,-1);
    tracep->declBit(c+147,"apb_bridge_valid", false,-1);
    tracep->declBus(c+122,"apb_bridge_rdata", false,-1, 31,0);
    tracep->declBit(c+123,"apb_bridge_ready", false,-1);
    tracep->declBit(c+32,"sim_exit_ready", false,-1);
    tracep->declBus(c+124,"PADDR_cpu", false,-1, 31,0);
    tracep->declBit(c+125,"PSEL_cpu", false,-1);
    tracep->declBit(c+126,"PENABLE_cpu", false,-1);
    tracep->declBit(c+127,"PWRITE_cpu", false,-1);
    tracep->declBus(c+128,"PWDATA_cpu", false,-1, 31,0);
    tracep->declBus(c+129,"PRDATA_cpu", false,-1, 31,0);
    tracep->declBit(c+130,"PREADY_cpu", false,-1);
    tracep->declBus(c+3,"PADDR_periph", false,-1, 31,0);
    tracep->declBit(c+4,"PSEL_periph", false,-1);
    tracep->declBit(c+5,"PENABLE_periph", false,-1);
    tracep->declBit(c+6,"PWRITE_periph", false,-1);
    tracep->declBus(c+7,"PWDATA_periph", false,-1, 31,0);
    tracep->declBus(c+8,"PRDATA_periph", false,-1, 31,0);
    tracep->declBit(c+9,"PREADY_periph", false,-1);
    tracep->declBit(c+10,"psel_uart", false,-1);
    tracep->declBit(c+11,"psel_gpio", false,-1);
    tracep->declBit(c+12,"psel_timer", false,-1);
    tracep->declBus(c+13,"prdata_uart", false,-1, 31,0);
    tracep->declBit(c+14,"pready_uart", false,-1);
    tracep->declBus(c+15,"prdata_gpio", false,-1, 31,0);
    tracep->declBit(c+301,"pready_gpio", false,-1);
    tracep->declBus(c+16,"prdata_timer", false,-1, 31,0);
    tracep->declBit(c+301,"pready_timer", false,-1);
    tracep->pushNamePrefix("apb_cdc ");
    tracep->declBit(c+282,"clk_cpu", false,-1);
    tracep->declBit(c+283,"rst_n_cpu", false,-1);
    tracep->declBus(c+124,"PADDR_cpu", false,-1, 31,0);
    tracep->declBit(c+125,"PSEL_cpu", false,-1);
    tracep->declBit(c+126,"PENABLE_cpu", false,-1);
    tracep->declBit(c+127,"PWRITE_cpu", false,-1);
    tracep->declBus(c+128,"PWDATA_cpu", false,-1, 31,0);
    tracep->declBus(c+129,"PRDATA_cpu", false,-1, 31,0);
    tracep->declBit(c+130,"PREADY_cpu", false,-1);
    tracep->declBit(c+289,"clk_periph", false,-1);
    tracep->declBit(c+283,"rst_n_periph", false,-1);
    tracep->declBus(c+3,"PADDR_periph", false,-1, 31,0);
    tracep->declBit(c+4,"PSEL_periph", false,-1);
    tracep->declBit(c+5,"PENABLE_periph", false,-1);
    tracep->declBit(c+6,"PWRITE_periph", false,-1);
    tracep->declBus(c+7,"PWDATA_periph", false,-1, 31,0);
    tracep->declBus(c+8,"PRDATA_periph", false,-1, 31,0);
    tracep->declBit(c+9,"PREADY_periph", false,-1);
    tracep->declBit(c+288,"clk_periph_en", false,-1);
    tracep->declBus(c+302,"CPU_STATE_IDLE", false,-1, 1,0);
    tracep->declBus(c+303,"CPU_STATE_WAIT", false,-1, 1,0);
    tracep->declBus(c+304,"CPU_STATE_DONE", false,-1, 1,0);
    tracep->declBus(c+305,"CPU_STATE_CLEAR", false,-1, 1,0);
    tracep->declBus(c+131,"cpu_state", false,-1, 1,0);
    tracep->declBit(c+132,"req_cpu", false,-1);
    tracep->declBus(c+133,"addr_hold", false,-1, 31,0);
    tracep->declBus(c+134,"wdata_hold", false,-1, 31,0);
    tracep->declBit(c+135,"write_hold", false,-1);
    tracep->declBus(c+136,"rdata_hold", false,-1, 31,0);
    tracep->declBus(c+302,"PERIPH_STATE_IDLE", false,-1, 1,0);
    tracep->declBus(c+303,"PERIPH_STATE_SETUP", false,-1, 1,0);
    tracep->declBus(c+304,"PERIPH_STATE_ACCESS", false,-1, 1,0);
    tracep->declBus(c+305,"PERIPH_STATE_HOLD", false,-1, 1,0);
    tracep->declBus(c+17,"periph_state", false,-1, 1,0);
    tracep->declBit(c+290,"ack_periph", false,-1);
    tracep->declBus(c+291,"PRDATA_from_periph", false,-1, 31,0);
    tracep->declBit(c+292,"req_periph_sync", false,-1);
    tracep->declBit(c+148,"ack_cpu_sync", false,-1);
    tracep->pushNamePrefix("sync_ack ");
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+290,"async_in", false,-1);
    tracep->declBit(c+148,"sync_out", false,-1);
    tracep->declBit(c+149,"sync_ff1", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("sync_req ");
    tracep->declBit(c+289,"clk", false,-1);
    tracep->declBit(c+132,"async_in", false,-1);
    tracep->declBit(c+292,"sync_out", false,-1);
    tracep->declBit(c+293,"sync_ff1", false,-1);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("apb_master ");
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+283,"rst_n", false,-1);
    tracep->declBit(c+147,"mem_valid", false,-1);
    tracep->declBit(c+123,"mem_ready", false,-1);
    tracep->declBus(c+140,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+141,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+142,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+122,"mem_rdata", false,-1, 31,0);
    tracep->declBus(c+124,"PADDR", false,-1, 31,0);
    tracep->declBit(c+125,"PSEL", false,-1);
    tracep->declBit(c+126,"PENABLE", false,-1);
    tracep->declBit(c+127,"PWRITE", false,-1);
    tracep->declBus(c+128,"PWDATA", false,-1, 31,0);
    tracep->declBus(c+129,"PRDATA", false,-1, 31,0);
    tracep->declBit(c+130,"PREADY", false,-1);
    tracep->declBus(c+302,"STATE_IDLE", false,-1, 1,0);
    tracep->declBus(c+303,"STATE_SETUP", false,-1, 1,0);
    tracep->declBus(c+304,"STATE_ACCESS", false,-1, 1,0);
    tracep->declBus(c+137,"state", false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("cpu ");
    tracep->declBus(c+306,"ENABLE_COUNTERS", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_COUNTERS64", false,-1, 0,0);
    tracep->declBus(c+307,"ENABLE_REGS_16_31", false,-1, 0,0);
    tracep->declBus(c+307,"ENABLE_REGS_DUALPORT", false,-1, 0,0);
    tracep->declBus(c+306,"LATCHED_MEM_RDATA", false,-1, 0,0);
    tracep->declBus(c+307,"TWO_STAGE_SHIFT", false,-1, 0,0);
    tracep->declBus(c+307,"BARREL_SHIFTER", false,-1, 0,0);
    tracep->declBus(c+306,"TWO_CYCLE_COMPARE", false,-1, 0,0);
    tracep->declBus(c+306,"TWO_CYCLE_ALU", false,-1, 0,0);
    tracep->declBus(c+306,"COMPRESSED_ISA", false,-1, 0,0);
    tracep->declBus(c+307,"CATCH_MISALIGN", false,-1, 0,0);
    tracep->declBus(c+307,"CATCH_ILLINSN", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_PCPI", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_MUL", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_FAST_MUL", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_DIV", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_IRQ", false,-1, 0,0);
    tracep->declBus(c+307,"ENABLE_IRQ_QREGS", false,-1, 0,0);
    tracep->declBus(c+307,"ENABLE_IRQ_TIMER", false,-1, 0,0);
    tracep->declBus(c+306,"ENABLE_TRACE", false,-1, 0,0);
    tracep->declBus(c+306,"REGS_INIT_ZERO", false,-1, 0,0);
    tracep->declBus(c+308,"MASKED_IRQ", false,-1, 31,0);
    tracep->declBus(c+309,"LATCHED_IRQ", false,-1, 31,0);
    tracep->declBus(c+308,"PROGADDR_RESET", false,-1, 31,0);
    tracep->declBus(c+310,"PROGADDR_IRQ", false,-1, 31,0);
    tracep->declBus(c+309,"STACKADDR", false,-1, 31,0);
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+283,"resetn", false,-1);
    tracep->declBit(c+138,"trap", false,-1);
    tracep->declBit(c+139,"mem_valid", false,-1);
    tracep->declBit(c+150,"mem_instr", false,-1);
    tracep->declBit(c+277,"mem_ready", false,-1);
    tracep->declBus(c+140,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+141,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+142,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+278,"mem_rdata", false,-1, 31,0);
    tracep->declBit(c+294,"mem_la_read", false,-1);
    tracep->declBit(c+295,"mem_la_write", false,-1);
    tracep->declBus(c+151,"mem_la_addr", false,-1, 31,0);
    tracep->declBus(c+152,"mem_la_wdata", false,-1, 31,0);
    tracep->declBus(c+153,"mem_la_wstrb", false,-1, 3,0);
    tracep->declBit(c+33,"pcpi_valid", false,-1);
    tracep->declBus(c+34,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+154,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+155,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+311,"pcpi_wr", false,-1);
    tracep->declBus(c+312,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+313,"pcpi_wait", false,-1);
    tracep->declBit(c+314,"pcpi_ready", false,-1);
    tracep->declBus(c+315,"irq", false,-1, 31,0);
    tracep->declBus(c+35,"eoi", false,-1, 31,0);
    tracep->declBit(c+36,"trace_valid", false,-1);
    tracep->declQuad(c+37,"trace_data", false,-1, 35,0);
    tracep->declBus(c+316,"irq_timer", false,-1, 31,0);
    tracep->declBus(c+317,"irq_ebreak", false,-1, 31,0);
    tracep->declBus(c+318,"irq_buserror", false,-1, 31,0);
    tracep->declBus(c+319,"irqregs_offset", false,-1, 31,0);
    tracep->declBus(c+319,"regfile_size", false,-1, 31,0);
    tracep->declBus(c+320,"regindex_bits", false,-1, 31,0);
    tracep->declBus(c+306,"WITH_PCPI", false,-1, 0,0);
    tracep->declQuad(c+321,"TRACE_BRANCH", false,-1, 35,0);
    tracep->declQuad(c+323,"TRACE_ADDR", false,-1, 35,0);
    tracep->declQuad(c+325,"TRACE_IRQ", false,-1, 35,0);
    tracep->declQuad(c+39,"count_cycle", false,-1, 63,0);
    tracep->declQuad(c+41,"count_instr", false,-1, 63,0);
    tracep->declBus(c+156,"reg_pc", false,-1, 31,0);
    tracep->declBus(c+157,"reg_next_pc", false,-1, 31,0);
    tracep->declBus(c+154,"reg_op1", false,-1, 31,0);
    tracep->declBus(c+155,"reg_op2", false,-1, 31,0);
    tracep->declBus(c+158,"reg_out", false,-1, 31,0);
    tracep->declBus(c+159,"reg_sh", false,-1, 4,0);
    tracep->declBus(c+43,"next_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+44,"dbg_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+45,"dbg_insn_addr", false,-1, 31,0);
    tracep->declBit(c+139,"dbg_mem_valid", false,-1);
    tracep->declBit(c+150,"dbg_mem_instr", false,-1);
    tracep->declBit(c+277,"dbg_mem_ready", false,-1);
    tracep->declBus(c+140,"dbg_mem_addr", false,-1, 31,0);
    tracep->declBus(c+141,"dbg_mem_wdata", false,-1, 31,0);
    tracep->declBus(c+142,"dbg_mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+278,"dbg_mem_rdata", false,-1, 31,0);
    tracep->declBus(c+160,"next_pc", false,-1, 31,0);
    tracep->declBit(c+161,"irq_delay", false,-1);
    tracep->declBit(c+162,"irq_active", false,-1);
    tracep->declBus(c+46,"irq_mask", false,-1, 31,0);
    tracep->declBus(c+47,"irq_pending", false,-1, 31,0);
    tracep->declBus(c+163,"timer", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+48+i*1,"cpuregs", true,(i+0), 31,0);
    }
    tracep->declBus(c+327,"i", false,-1, 31,0);
    tracep->declBit(c+328,"pcpi_mul_wr", false,-1);
    tracep->declBus(c+308,"pcpi_mul_rd", false,-1, 31,0);
    tracep->declBit(c+328,"pcpi_mul_wait", false,-1);
    tracep->declBit(c+328,"pcpi_mul_ready", false,-1);
    tracep->declBit(c+328,"pcpi_div_wr", false,-1);
    tracep->declBus(c+308,"pcpi_div_rd", false,-1, 31,0);
    tracep->declBit(c+328,"pcpi_div_wait", false,-1);
    tracep->declBit(c+328,"pcpi_div_ready", false,-1);
    tracep->declBit(c+328,"pcpi_int_wr", false,-1);
    tracep->declBus(c+308,"pcpi_int_rd", false,-1, 31,0);
    tracep->declBit(c+328,"pcpi_int_wait", false,-1);
    tracep->declBit(c+328,"pcpi_int_ready", false,-1);
    tracep->declBus(c+164,"mem_state", false,-1, 1,0);
    tracep->declBus(c+165,"mem_wordsize", false,-1, 1,0);
    tracep->declBus(c+279,"mem_rdata_word", false,-1, 31,0);
    tracep->declBus(c+166,"mem_rdata_q", false,-1, 31,0);
    tracep->declBit(c+167,"mem_do_prefetch", false,-1);
    tracep->declBit(c+168,"mem_do_rinst", false,-1);
    tracep->declBit(c+169,"mem_do_rdata", false,-1);
    tracep->declBit(c+170,"mem_do_wdata", false,-1);
    tracep->declBit(c+280,"mem_xfer", false,-1);
    tracep->declBit(c+171,"mem_la_secondword", false,-1);
    tracep->declBit(c+80,"mem_la_firstword_reg", false,-1);
    tracep->declBit(c+81,"last_mem_valid", false,-1);
    tracep->declBit(c+328,"mem_la_firstword", false,-1);
    tracep->declBit(c+328,"mem_la_firstword_xfer", false,-1);
    tracep->declBit(c+82,"prefetched_high_word", false,-1);
    tracep->declBit(c+296,"clear_prefetched_high_word", false,-1);
    tracep->declBus(c+329,"mem_16bit_buffer", false,-1, 15,0);
    tracep->declBus(c+281,"mem_rdata_latched_noshuffle", false,-1, 31,0);
    tracep->declBus(c+281,"mem_rdata_latched", false,-1, 31,0);
    tracep->declBit(c+328,"mem_la_use_prefetched_high_word", false,-1);
    tracep->declBit(c+172,"mem_busy", false,-1);
    tracep->declBit(c+297,"mem_done", false,-1);
    tracep->declBit(c+173,"instr_lui", false,-1);
    tracep->declBit(c+174,"instr_auipc", false,-1);
    tracep->declBit(c+175,"instr_jal", false,-1);
    tracep->declBit(c+176,"instr_jalr", false,-1);
    tracep->declBit(c+177,"instr_beq", false,-1);
    tracep->declBit(c+178,"instr_bne", false,-1);
    tracep->declBit(c+179,"instr_blt", false,-1);
    tracep->declBit(c+180,"instr_bge", false,-1);
    tracep->declBit(c+181,"instr_bltu", false,-1);
    tracep->declBit(c+182,"instr_bgeu", false,-1);
    tracep->declBit(c+183,"instr_lb", false,-1);
    tracep->declBit(c+184,"instr_lh", false,-1);
    tracep->declBit(c+185,"instr_lw", false,-1);
    tracep->declBit(c+186,"instr_lbu", false,-1);
    tracep->declBit(c+187,"instr_lhu", false,-1);
    tracep->declBit(c+188,"instr_sb", false,-1);
    tracep->declBit(c+189,"instr_sh", false,-1);
    tracep->declBit(c+190,"instr_sw", false,-1);
    tracep->declBit(c+191,"instr_addi", false,-1);
    tracep->declBit(c+192,"instr_slti", false,-1);
    tracep->declBit(c+193,"instr_sltiu", false,-1);
    tracep->declBit(c+194,"instr_xori", false,-1);
    tracep->declBit(c+195,"instr_ori", false,-1);
    tracep->declBit(c+196,"instr_andi", false,-1);
    tracep->declBit(c+197,"instr_slli", false,-1);
    tracep->declBit(c+198,"instr_srli", false,-1);
    tracep->declBit(c+199,"instr_srai", false,-1);
    tracep->declBit(c+200,"instr_add", false,-1);
    tracep->declBit(c+201,"instr_sub", false,-1);
    tracep->declBit(c+202,"instr_sll", false,-1);
    tracep->declBit(c+203,"instr_slt", false,-1);
    tracep->declBit(c+204,"instr_sltu", false,-1);
    tracep->declBit(c+205,"instr_xor", false,-1);
    tracep->declBit(c+206,"instr_srl", false,-1);
    tracep->declBit(c+207,"instr_sra", false,-1);
    tracep->declBit(c+208,"instr_or", false,-1);
    tracep->declBit(c+209,"instr_and", false,-1);
    tracep->declBit(c+83,"instr_rdcycle", false,-1);
    tracep->declBit(c+84,"instr_rdcycleh", false,-1);
    tracep->declBit(c+85,"instr_rdinstr", false,-1);
    tracep->declBit(c+86,"instr_rdinstrh", false,-1);
    tracep->declBit(c+87,"instr_ecall_ebreak", false,-1);
    tracep->declBit(c+88,"instr_fence", false,-1);
    tracep->declBit(c+89,"instr_getq", false,-1);
    tracep->declBit(c+90,"instr_setq", false,-1);
    tracep->declBit(c+210,"instr_retirq", false,-1);
    tracep->declBit(c+91,"instr_maskirq", false,-1);
    tracep->declBit(c+92,"instr_waitirq", false,-1);
    tracep->declBit(c+93,"instr_timer", false,-1);
    tracep->declBit(c+211,"instr_trap", false,-1);
    tracep->declBus(c+212,"decoded_rd", false,-1, 4,0);
    tracep->declBus(c+94,"decoded_rs1", false,-1, 4,0);
    tracep->declBus(c+213,"decoded_rs2", false,-1, 4,0);
    tracep->declBus(c+214,"decoded_imm", false,-1, 31,0);
    tracep->declBus(c+215,"decoded_imm_j", false,-1, 31,0);
    tracep->declBit(c+216,"decoder_trigger", false,-1);
    tracep->declBit(c+217,"decoder_trigger_q", false,-1);
    tracep->declBit(c+218,"decoder_pseudo_trigger", false,-1);
    tracep->declBit(c+95,"decoder_pseudo_trigger_q", false,-1);
    tracep->declBit(c+210,"compressed_instr", false,-1);
    tracep->declBit(c+219,"is_lui_auipc_jal", false,-1);
    tracep->declBit(c+220,"is_lb_lh_lw_lbu_lhu", false,-1);
    tracep->declBit(c+221,"is_slli_srli_srai", false,-1);
    tracep->declBit(c+222,"is_jalr_addi_slti_sltiu_xori_ori_andi", false,-1);
    tracep->declBit(c+223,"is_sb_sh_sw", false,-1);
    tracep->declBit(c+224,"is_sll_srl_sra", false,-1);
    tracep->declBit(c+225,"is_lui_auipc_jal_jalr_addi_add_sub", false,-1);
    tracep->declBit(c+226,"is_slti_blt_slt", false,-1);
    tracep->declBit(c+227,"is_sltiu_bltu_sltu", false,-1);
    tracep->declBit(c+228,"is_beq_bne_blt_bge_bltu_bgeu", false,-1);
    tracep->declBit(c+229,"is_lbu_lhu_lw", false,-1);
    tracep->declBit(c+230,"is_alu_reg_imm", false,-1);
    tracep->declBit(c+231,"is_alu_reg_reg", false,-1);
    tracep->declBit(c+232,"is_compare", false,-1);
    tracep->declBit(c+96,"is_rdcycle_rdcycleh_rdinstr_rdinstrh", false,-1);
    tracep->declQuad(c+233,"new_ascii_instr", false,-1, 63,0);
    tracep->declQuad(c+235,"dbg_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+237,"dbg_insn_imm", false,-1, 31,0);
    tracep->declBus(c+97,"dbg_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+238,"dbg_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+239,"dbg_insn_rd", false,-1, 4,0);
    tracep->declBus(c+240,"dbg_rs1val", false,-1, 31,0);
    tracep->declBus(c+241,"dbg_rs2val", false,-1, 31,0);
    tracep->declBit(c+242,"dbg_rs1val_valid", false,-1);
    tracep->declBit(c+243,"dbg_rs2val_valid", false,-1);
    tracep->declQuad(c+98,"q_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+100,"q_insn_imm", false,-1, 31,0);
    tracep->declBus(c+101,"q_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+102,"q_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+103,"q_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+104,"q_insn_rd", false,-1, 4,0);
    tracep->declBit(c+105,"dbg_next", false,-1);
    tracep->declBit(c+244,"launch_next_insn", false,-1);
    tracep->declBit(c+106,"dbg_valid_insn", false,-1);
    tracep->declQuad(c+107,"cached_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+109,"cached_insn_imm", false,-1, 31,0);
    tracep->declBus(c+110,"cached_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+111,"cached_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+112,"cached_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+113,"cached_insn_rd", false,-1, 4,0);
    tracep->declBus(c+330,"cpu_state_trap", false,-1, 7,0);
    tracep->declBus(c+331,"cpu_state_fetch", false,-1, 7,0);
    tracep->declBus(c+332,"cpu_state_ld_rs1", false,-1, 7,0);
    tracep->declBus(c+333,"cpu_state_ld_rs2", false,-1, 7,0);
    tracep->declBus(c+334,"cpu_state_exec", false,-1, 7,0);
    tracep->declBus(c+335,"cpu_state_shift", false,-1, 7,0);
    tracep->declBus(c+336,"cpu_state_stmem", false,-1, 7,0);
    tracep->declBus(c+337,"cpu_state_ldmem", false,-1, 7,0);
    tracep->declBus(c+245,"cpu_state", false,-1, 7,0);
    tracep->declBus(c+114,"irq_state", false,-1, 1,0);
    tracep->declArray(c+246,"dbg_ascii_state", false,-1, 127,0);
    tracep->declBit(c+250,"set_mem_do_rinst", false,-1);
    tracep->declBit(c+251,"set_mem_do_rdata", false,-1);
    tracep->declBit(c+252,"set_mem_do_wdata", false,-1);
    tracep->declBit(c+253,"latched_store", false,-1);
    tracep->declBit(c+254,"latched_stalu", false,-1);
    tracep->declBit(c+255,"latched_branch", false,-1);
    tracep->declBit(c+256,"latched_compr", false,-1);
    tracep->declBit(c+115,"latched_trace", false,-1);
    tracep->declBit(c+257,"latched_is_lu", false,-1);
    tracep->declBit(c+258,"latched_is_lh", false,-1);
    tracep->declBit(c+259,"latched_is_lb", false,-1);
    tracep->declBus(c+260,"latched_rd", false,-1, 4,0);
    tracep->declBus(c+261,"current_pc", false,-1, 31,0);
    tracep->declBus(c+338,"pcpi_timeout_counter", false,-1, 3,0);
    tracep->declBit(c+116,"pcpi_timeout", false,-1);
    tracep->declBus(c+117,"next_irq_pending", false,-1, 31,0);
    tracep->declBit(c+262,"do_waitirq", false,-1);
    tracep->declBus(c+263,"alu_out", false,-1, 31,0);
    tracep->declBus(c+264,"alu_out_q", false,-1, 31,0);
    tracep->declBit(c+265,"alu_out_0", false,-1);
    tracep->declBit(c+118,"alu_out_0_q", false,-1);
    tracep->declBit(c+119,"alu_wait", false,-1);
    tracep->declBit(c+120,"alu_wait_2", false,-1);
    tracep->declBus(c+266,"alu_add_sub", false,-1, 31,0);
    tracep->declBus(c+267,"alu_shl", false,-1, 31,0);
    tracep->declBus(c+268,"alu_shr", false,-1, 31,0);
    tracep->declBit(c+269,"alu_eq", false,-1);
    tracep->declBit(c+270,"alu_ltu", false,-1);
    tracep->declBit(c+271,"alu_lts", false,-1);
    tracep->declBit(c+121,"clear_prefetched_high_word_q", false,-1);
    tracep->declBit(c+272,"cpuregs_write", false,-1);
    tracep->declBus(c+273,"cpuregs_wrdata", false,-1, 31,0);
    tracep->declBus(c+274,"cpuregs_rs1", false,-1, 31,0);
    tracep->declBus(c+275,"cpuregs_rs2", false,-1, 31,0);
    tracep->declBus(c+339,"decoded_rs", false,-1, 4,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("gpio_peripheral ");
    tracep->declBit(c+289,"PCLK", false,-1);
    tracep->declBit(c+283,"PRESETn", false,-1);
    tracep->declBit(c+11,"PSEL", false,-1);
    tracep->declBit(c+5,"PENABLE", false,-1);
    tracep->declBit(c+6,"PWRITE", false,-1);
    tracep->declBus(c+18,"PADDR", false,-1, 7,0);
    tracep->declBus(c+7,"PWDATA", false,-1, 31,0);
    tracep->declBus(c+15,"PRDATA", false,-1, 31,0);
    tracep->declBit(c+301,"PREADY", false,-1);
    tracep->declBus(c+1,"gpio_out", false,-1, 31,0);
    tracep->declBus(c+1,"gpio_in", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("periph_clk_div ");
    tracep->declBit(c+282,"clk_in", false,-1);
    tracep->declBit(c+298,"rst", false,-1);
    tracep->declBit(c+287,"clk_out", false,-1);
    tracep->declBus(c+299,"counter", false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("periph_icg ");
    tracep->declBit(c+287,"clk_in", false,-1);
    tracep->declBit(c+288,"en", false,-1);
    tracep->declBit(c+289,"clk_out", false,-1);
    tracep->declBit(c+300,"en_latch", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("ram ");
    tracep->declBus(c+340,"MEM_SIZE", false,-1, 31,0);
    tracep->declBit(c+282,"clk", false,-1);
    tracep->declBit(c+283,"rst_n", false,-1);
    tracep->declBit(c+146,"valid", false,-1);
    tracep->declBus(c+140,"addr", false,-1, 31,0);
    tracep->declBus(c+141,"wdata", false,-1, 31,0);
    tracep->declBus(c+142,"wstrb", false,-1, 3,0);
    tracep->declBus(c+30,"rdata", false,-1, 31,0);
    tracep->declBit(c+31,"ready", false,-1);
    tracep->declBus(c+341,"WORDS", false,-1, 31,0);
    tracep->declBus(c+276,"word_idx", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("timer_peripheral ");
    tracep->declBus(c+342,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+289,"PCLK", false,-1);
    tracep->declBit(c+283,"PRESETn", false,-1);
    tracep->declBit(c+12,"PSEL", false,-1);
    tracep->declBit(c+5,"PENABLE", false,-1);
    tracep->declBit(c+6,"PWRITE", false,-1);
    tracep->declBus(c+18,"PADDR", false,-1, 7,0);
    tracep->declBus(c+7,"PWDATA", false,-1, 31,0);
    tracep->declBus(c+16,"PRDATA", false,-1, 31,0);
    tracep->declBit(c+301,"PREADY", false,-1);
    tracep->declBit(c+2,"timer_done", false,-1);
    tracep->declBus(c+19,"load_val", false,-1, 31,0);
    tracep->declBus(c+20,"count", false,-1, 31,0);
    tracep->declBit(c+21,"running", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("uart_peripheral ");
    tracep->declBit(c+289,"clk", false,-1);
    tracep->declBit(c+283,"rst_n", false,-1);
    tracep->declBus(c+3,"PADDR", false,-1, 31,0);
    tracep->declBus(c+7,"PWDATA", false,-1, 31,0);
    tracep->declBit(c+6,"PWRITE", false,-1);
    tracep->declBit(c+10,"PSEL", false,-1);
    tracep->declBit(c+5,"PENABLE", false,-1);
    tracep->declBus(c+13,"PRDATA", false,-1, 31,0);
    tracep->declBit(c+14,"PREADY", false,-1);
    tracep->declBus(c+22,"tx_data", false,-1, 7,0);
    tracep->declBit(c+23,"tx_write", false,-1);
    tracep->declBus(c+24,"rx_data", false,-1, 7,0);
    tracep->declBit(c+25,"rx_ready", false,-1);
    tracep->declBit(c+26,"tx_busy", false,-1);
    tracep->pushNamePrefix("uart_inst ");
    tracep->declBit(c+289,"clk", false,-1);
    tracep->declBit(c+283,"rst_n", false,-1);
    tracep->declBus(c+22,"tx_data", false,-1, 7,0);
    tracep->declBit(c+23,"tx_write", false,-1);
    tracep->declBus(c+24,"rx_data", false,-1, 7,0);
    tracep->declBit(c+25,"rx_ready", false,-1);
    tracep->declBit(c+26,"tx_busy", false,-1);
    tracep->declBus(c+27,"tx_reg", false,-1, 7,0);
    tracep->popNamePrefix(4);
}

VL_ATTR_COLD void Vtb_soc___024root__trace_init_top(Vtb_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_soc___024root__trace_init_top\n"); );
    // Body
    Vtb_soc___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtb_soc___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtb_soc___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtb_soc___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtb_soc___024root__trace_register(Vtb_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_soc___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtb_soc___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtb_soc___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtb_soc___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtb_soc___024root__trace_full_sub_0(Vtb_soc___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtb_soc___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_soc___024root__trace_full_top_0\n"); );
    // Init
    Vtb_soc___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_soc___024root*>(voidSelf);
    Vtb_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtb_soc___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtb_soc___024root__trace_full_sub_0(Vtb_soc___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_soc___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelf->tb_soc__DOT__gpio_out),32);
    bufp->fullBit(oldp+2,(vlSelf->tb_soc__DOT__timer_done));
    bufp->fullIData(oldp+3,(vlSelf->tb_soc__DOT__dut__DOT__PADDR_periph),32);
    bufp->fullBit(oldp+4,(vlSelf->tb_soc__DOT__dut__DOT__PSEL_periph));
    bufp->fullBit(oldp+5,(vlSelf->tb_soc__DOT__dut__DOT__PENABLE_periph));
    bufp->fullBit(oldp+6,(vlSelf->tb_soc__DOT__dut__DOT__PWRITE_periph));
    bufp->fullIData(oldp+7,(vlSelf->tb_soc__DOT__dut__DOT__PWDATA_periph),32);
    bufp->fullIData(oldp+8,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__psel_uart)
                              ? vlSelf->tb_soc__DOT__dut__DOT__prdata_uart
                              : ((IData)(vlSelf->tb_soc__DOT__dut__DOT__psel_gpio)
                                  ? vlSelf->tb_soc__DOT__dut__DOT__prdata_gpio
                                  : ((IData)(vlSelf->tb_soc__DOT__dut__DOT__psel_timer)
                                      ? vlSelf->tb_soc__DOT__dut__DOT__prdata_timer
                                      : 0U)))),32);
    bufp->fullBit(oldp+9,((1U & ((~ (IData)(vlSelf->tb_soc__DOT__dut__DOT__psel_uart)) 
                                 | (IData)(vlSelf->tb_soc__DOT__dut__DOT__pready_uart)))));
    bufp->fullBit(oldp+10,(vlSelf->tb_soc__DOT__dut__DOT__psel_uart));
    bufp->fullBit(oldp+11,(vlSelf->tb_soc__DOT__dut__DOT__psel_gpio));
    bufp->fullBit(oldp+12,(vlSelf->tb_soc__DOT__dut__DOT__psel_timer));
    bufp->fullIData(oldp+13,(vlSelf->tb_soc__DOT__dut__DOT__prdata_uart),32);
    bufp->fullBit(oldp+14,(vlSelf->tb_soc__DOT__dut__DOT__pready_uart));
    bufp->fullIData(oldp+15,(vlSelf->tb_soc__DOT__dut__DOT__prdata_gpio),32);
    bufp->fullIData(oldp+16,(vlSelf->tb_soc__DOT__dut__DOT__prdata_timer),32);
    bufp->fullCData(oldp+17,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__periph_state),2);
    bufp->fullCData(oldp+18,((0xffU & vlSelf->tb_soc__DOT__dut__DOT__PADDR_periph)),8);
    bufp->fullIData(oldp+19,(vlSelf->tb_soc__DOT__dut__DOT__timer_peripheral__DOT__load_val),32);
    bufp->fullIData(oldp+20,(vlSelf->tb_soc__DOT__dut__DOT__timer_peripheral__DOT__count),32);
    bufp->fullBit(oldp+21,(vlSelf->tb_soc__DOT__dut__DOT__timer_peripheral__DOT__running));
    bufp->fullCData(oldp+22,((0xffU & vlSelf->tb_soc__DOT__dut__DOT__PWDATA_periph)),8);
    bufp->fullBit(oldp+23,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__psel_uart) 
                            & ((IData)(vlSelf->tb_soc__DOT__dut__DOT__PENABLE_periph) 
                               & ((IData)(vlSelf->tb_soc__DOT__dut__DOT__PWRITE_periph) 
                                  & (IData)(vlSelf->tb_soc__DOT__dut__DOT__pready_uart))))));
    bufp->fullCData(oldp+24,(vlSelf->tb_soc__DOT__dut__DOT__uart_peripheral__DOT__rx_data),8);
    bufp->fullBit(oldp+25,(vlSelf->tb_soc__DOT__dut__DOT__uart_peripheral__DOT__rx_ready));
    bufp->fullBit(oldp+26,(vlSelf->tb_soc__DOT__dut__DOT__uart_peripheral__DOT__tx_busy));
    bufp->fullCData(oldp+27,(vlSelf->tb_soc__DOT__dut__DOT__uart_peripheral__DOT__uart_inst__DOT__tx_reg),8);
    bufp->fullBit(oldp+28,(vlSelf->tb_soc__DOT__sim_exit_req));
    bufp->fullIData(oldp+29,(vlSelf->tb_soc__DOT__sim_exit_code),32);
    bufp->fullIData(oldp+30,(vlSelf->tb_soc__DOT__dut__DOT__ram_rdata),32);
    bufp->fullBit(oldp+31,(vlSelf->tb_soc__DOT__dut__DOT__ram_ready));
    bufp->fullBit(oldp+32,(vlSelf->tb_soc__DOT__dut__DOT__sim_exit_ready));
    bufp->fullBit(oldp+33,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_valid));
    bufp->fullIData(oldp+34,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+35,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__eoi),32);
    bufp->fullBit(oldp+36,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__trace_valid));
    bufp->fullQData(oldp+37,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__trace_data),36);
    bufp->fullQData(oldp+39,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__count_cycle),64);
    bufp->fullQData(oldp+41,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__count_instr),64);
    bufp->fullIData(oldp+43,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__next_insn_opcode),32);
    bufp->fullIData(oldp+44,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+45,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_addr),32);
    bufp->fullIData(oldp+46,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq_mask),32);
    bufp->fullIData(oldp+47,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq_pending),32);
    bufp->fullIData(oldp+48,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[0]),32);
    bufp->fullIData(oldp+49,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[1]),32);
    bufp->fullIData(oldp+50,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[2]),32);
    bufp->fullIData(oldp+51,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[3]),32);
    bufp->fullIData(oldp+52,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[4]),32);
    bufp->fullIData(oldp+53,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[5]),32);
    bufp->fullIData(oldp+54,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[6]),32);
    bufp->fullIData(oldp+55,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[7]),32);
    bufp->fullIData(oldp+56,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[8]),32);
    bufp->fullIData(oldp+57,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[9]),32);
    bufp->fullIData(oldp+58,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[10]),32);
    bufp->fullIData(oldp+59,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[11]),32);
    bufp->fullIData(oldp+60,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[12]),32);
    bufp->fullIData(oldp+61,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[13]),32);
    bufp->fullIData(oldp+62,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[14]),32);
    bufp->fullIData(oldp+63,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[15]),32);
    bufp->fullIData(oldp+64,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[16]),32);
    bufp->fullIData(oldp+65,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[17]),32);
    bufp->fullIData(oldp+66,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[18]),32);
    bufp->fullIData(oldp+67,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[19]),32);
    bufp->fullIData(oldp+68,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[20]),32);
    bufp->fullIData(oldp+69,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[21]),32);
    bufp->fullIData(oldp+70,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[22]),32);
    bufp->fullIData(oldp+71,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[23]),32);
    bufp->fullIData(oldp+72,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[24]),32);
    bufp->fullIData(oldp+73,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[25]),32);
    bufp->fullIData(oldp+74,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[26]),32);
    bufp->fullIData(oldp+75,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[27]),32);
    bufp->fullIData(oldp+76,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[28]),32);
    bufp->fullIData(oldp+77,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[29]),32);
    bufp->fullIData(oldp+78,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[30]),32);
    bufp->fullIData(oldp+79,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs[31]),32);
    bufp->fullBit(oldp+80,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_firstword_reg));
    bufp->fullBit(oldp+81,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__last_mem_valid));
    bufp->fullBit(oldp+82,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__prefetched_high_word));
    bufp->fullBit(oldp+83,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdcycle));
    bufp->fullBit(oldp+84,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdcycleh));
    bufp->fullBit(oldp+85,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdinstr));
    bufp->fullBit(oldp+86,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdinstrh));
    bufp->fullBit(oldp+87,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_ecall_ebreak));
    bufp->fullBit(oldp+88,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_fence));
    bufp->fullBit(oldp+89,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_getq));
    bufp->fullBit(oldp+90,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_setq));
    bufp->fullBit(oldp+91,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_maskirq));
    bufp->fullBit(oldp+92,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_waitirq));
    bufp->fullBit(oldp+93,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_timer));
    bufp->fullCData(oldp+94,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoded_rs1),5);
    bufp->fullBit(oldp+95,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoder_pseudo_trigger_q));
    bufp->fullBit(oldp+96,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdcycle) 
                            | ((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdcycleh) 
                               | ((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdinstr) 
                                  | (IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_rdinstrh))))));
    bufp->fullCData(oldp+97,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_rs1),5);
    bufp->fullQData(oldp+98,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_ascii_instr),64);
    bufp->fullIData(oldp+100,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_insn_imm),32);
    bufp->fullIData(oldp+101,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_insn_opcode),32);
    bufp->fullCData(oldp+102,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_insn_rs1),5);
    bufp->fullCData(oldp+103,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_insn_rs2),5);
    bufp->fullCData(oldp+104,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__q_insn_rd),5);
    bufp->fullBit(oldp+105,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_next));
    bufp->fullBit(oldp+106,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_valid_insn));
    bufp->fullQData(oldp+107,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_ascii_instr),64);
    bufp->fullIData(oldp+109,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_insn_imm),32);
    bufp->fullIData(oldp+110,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_insn_opcode),32);
    bufp->fullCData(oldp+111,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_insn_rs1),5);
    bufp->fullCData(oldp+112,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_insn_rs2),5);
    bufp->fullCData(oldp+113,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cached_insn_rd),5);
    bufp->fullCData(oldp+114,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq_state),2);
    bufp->fullBit(oldp+115,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_trace));
    bufp->fullBit(oldp+116,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_timeout));
    bufp->fullIData(oldp+117,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__next_irq_pending),32);
    bufp->fullBit(oldp+118,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_out_0_q));
    bufp->fullBit(oldp+119,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_wait));
    bufp->fullBit(oldp+120,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_wait_2));
    bufp->fullBit(oldp+121,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__clear_prefetched_high_word_q));
    bufp->fullIData(oldp+122,(vlSelf->tb_soc__DOT__dut__DOT__apb_bridge_rdata),32);
    bufp->fullBit(oldp+123,(vlSelf->tb_soc__DOT__dut__DOT__apb_bridge_ready));
    bufp->fullIData(oldp+124,(vlSelf->tb_soc__DOT__dut__DOT__PADDR_cpu),32);
    bufp->fullBit(oldp+125,(vlSelf->tb_soc__DOT__dut__DOT__PSEL_cpu));
    bufp->fullBit(oldp+126,(vlSelf->tb_soc__DOT__dut__DOT__PENABLE_cpu));
    bufp->fullBit(oldp+127,(vlSelf->tb_soc__DOT__dut__DOT__PWRITE_cpu));
    bufp->fullIData(oldp+128,(vlSelf->tb_soc__DOT__dut__DOT__PWDATA_cpu),32);
    bufp->fullIData(oldp+129,(vlSelf->tb_soc__DOT__dut__DOT__PRDATA_cpu),32);
    bufp->fullBit(oldp+130,(vlSelf->tb_soc__DOT__dut__DOT__PREADY_cpu));
    bufp->fullCData(oldp+131,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__cpu_state),2);
    bufp->fullBit(oldp+132,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__req_cpu));
    bufp->fullIData(oldp+133,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__addr_hold),32);
    bufp->fullIData(oldp+134,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__wdata_hold),32);
    bufp->fullBit(oldp+135,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__write_hold));
    bufp->fullIData(oldp+136,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__rdata_hold),32);
    bufp->fullCData(oldp+137,(vlSelf->tb_soc__DOT__dut__DOT__apb_master__DOT__state),2);
    bufp->fullBit(oldp+138,(vlSelf->tb_soc__DOT__trap));
    bufp->fullBit(oldp+139,(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_valid));
    bufp->fullIData(oldp+140,(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr),32);
    bufp->fullIData(oldp+141,(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_wdata),32);
    bufp->fullCData(oldp+142,(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_wstrb),4);
    bufp->fullBit(oldp+143,((0x4000U > vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr)));
    bufp->fullBit(oldp+144,(((0x10000000U <= vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr) 
                             & (0x10030000U > vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr))));
    bufp->fullBit(oldp+145,((0x80000004U == vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr)));
    bufp->fullBit(oldp+146,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_valid) 
                             & (0x4000U > vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr))));
    bufp->fullBit(oldp+147,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_valid) 
                             & ((0x10000000U <= vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr) 
                                & (0x10030000U > vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr)))));
    bufp->fullBit(oldp+148,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__ack_cpu_sync));
    bufp->fullBit(oldp+149,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__sync_ack__DOT__sync_ff1));
    bufp->fullBit(oldp+150,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_instr));
    bufp->fullIData(oldp+151,((((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_prefetch) 
                                | (IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_rinst))
                                ? (0xfffffffcU & vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__next_pc)
                                : (0xfffffffcU & vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1))),32);
    bufp->fullIData(oldp+152,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_wdata),32);
    bufp->fullCData(oldp+153,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_wstrb),4);
    bufp->fullIData(oldp+154,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1),32);
    bufp->fullIData(oldp+155,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op2),32);
    bufp->fullIData(oldp+156,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_pc),32);
    bufp->fullIData(oldp+157,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_next_pc),32);
    bufp->fullIData(oldp+158,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_out),32);
    bufp->fullCData(oldp+159,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_sh),5);
    bufp->fullIData(oldp+160,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__next_pc),32);
    bufp->fullBit(oldp+161,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq_delay));
    bufp->fullBit(oldp+162,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq_active));
    bufp->fullIData(oldp+163,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__timer),32);
    bufp->fullCData(oldp+164,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_state),2);
    bufp->fullCData(oldp+165,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_wordsize),2);
    bufp->fullIData(oldp+166,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_rdata_q),32);
    bufp->fullBit(oldp+167,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_prefetch));
    bufp->fullBit(oldp+168,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_rinst));
    bufp->fullBit(oldp+169,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_rdata));
    bufp->fullBit(oldp+170,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_wdata));
    bufp->fullBit(oldp+171,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_secondword));
    bufp->fullBit(oldp+172,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_do_prefetch) 
                             | (IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT____VdfgTmp_hb06275b1__0))));
    bufp->fullBit(oldp+173,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lui));
    bufp->fullBit(oldp+174,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_auipc));
    bufp->fullBit(oldp+175,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_jal));
    bufp->fullBit(oldp+176,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_jalr));
    bufp->fullBit(oldp+177,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_beq));
    bufp->fullBit(oldp+178,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_bne));
    bufp->fullBit(oldp+179,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_blt));
    bufp->fullBit(oldp+180,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_bge));
    bufp->fullBit(oldp+181,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_bltu));
    bufp->fullBit(oldp+182,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_bgeu));
    bufp->fullBit(oldp+183,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lb));
    bufp->fullBit(oldp+184,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lh));
    bufp->fullBit(oldp+185,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lw));
    bufp->fullBit(oldp+186,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lbu));
    bufp->fullBit(oldp+187,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_lhu));
    bufp->fullBit(oldp+188,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sb));
    bufp->fullBit(oldp+189,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sh));
    bufp->fullBit(oldp+190,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sw));
    bufp->fullBit(oldp+191,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_addi));
    bufp->fullBit(oldp+192,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_slti));
    bufp->fullBit(oldp+193,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sltiu));
    bufp->fullBit(oldp+194,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_xori));
    bufp->fullBit(oldp+195,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_ori));
    bufp->fullBit(oldp+196,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_andi));
    bufp->fullBit(oldp+197,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_slli));
    bufp->fullBit(oldp+198,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_srli));
    bufp->fullBit(oldp+199,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_srai));
    bufp->fullBit(oldp+200,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_add));
    bufp->fullBit(oldp+201,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sub));
    bufp->fullBit(oldp+202,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sll));
    bufp->fullBit(oldp+203,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_slt));
    bufp->fullBit(oldp+204,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sltu));
    bufp->fullBit(oldp+205,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_xor));
    bufp->fullBit(oldp+206,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_srl));
    bufp->fullBit(oldp+207,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sra));
    bufp->fullBit(oldp+208,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_or));
    bufp->fullBit(oldp+209,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_and));
    bufp->fullBit(oldp+210,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__compressed_instr));
    bufp->fullBit(oldp+211,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_trap));
    bufp->fullCData(oldp+212,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoded_rd),5);
    bufp->fullCData(oldp+213,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoded_rs2),5);
    bufp->fullIData(oldp+214,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoded_imm),32);
    bufp->fullIData(oldp+215,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoded_imm_j),32);
    bufp->fullBit(oldp+216,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoder_trigger));
    bufp->fullBit(oldp+217,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoder_trigger_q));
    bufp->fullBit(oldp+218,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+219,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_lui_auipc_jal));
    bufp->fullBit(oldp+220,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+221,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_slli_srli_srai));
    bufp->fullBit(oldp+222,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+223,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_sb_sh_sw));
    bufp->fullBit(oldp+224,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_sll_srl_sra));
    bufp->fullBit(oldp+225,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+226,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_slti_blt_slt));
    bufp->fullBit(oldp+227,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+228,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+229,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+230,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_alu_reg_imm));
    bufp->fullBit(oldp+231,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_alu_reg_reg));
    bufp->fullBit(oldp+232,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__is_compare));
    bufp->fullQData(oldp+233,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__new_ascii_instr),64);
    bufp->fullQData(oldp+235,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+237,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_imm),32);
    bufp->fullCData(oldp+238,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+239,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_insn_rd),5);
    bufp->fullIData(oldp+240,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_rs1val),32);
    bufp->fullIData(oldp+241,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_rs2val),32);
    bufp->fullBit(oldp+242,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_rs1val_valid));
    bufp->fullBit(oldp+243,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_rs2val_valid));
    bufp->fullBit(oldp+244,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__launch_next_insn));
    bufp->fullCData(oldp+245,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpu_state),8);
    bufp->fullWData(oldp+246,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_ascii_state),128);
    bufp->fullBit(oldp+250,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__set_mem_do_rinst));
    bufp->fullBit(oldp+251,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__set_mem_do_rdata));
    bufp->fullBit(oldp+252,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__set_mem_do_wdata));
    bufp->fullBit(oldp+253,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_store));
    bufp->fullBit(oldp+254,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_stalu));
    bufp->fullBit(oldp+255,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_branch));
    bufp->fullBit(oldp+256,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_compr));
    bufp->fullBit(oldp+257,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_is_lu));
    bufp->fullBit(oldp+258,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_is_lh));
    bufp->fullBit(oldp+259,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_is_lb));
    bufp->fullCData(oldp+260,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__latched_rd),5);
    bufp->fullIData(oldp+261,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__current_pc),32);
    bufp->fullBit(oldp+262,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__do_waitirq));
    bufp->fullIData(oldp+263,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_out),32);
    bufp->fullIData(oldp+264,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_out_q),32);
    bufp->fullBit(oldp+265,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_out_0));
    bufp->fullIData(oldp+266,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sub)
                                ? (vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1 
                                   - vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op2)
                                : (vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1 
                                   + vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+267,((vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1 
                               << (0x1fU & vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+268,((IData)((0x1ffffffffULL 
                                       & VL_SHIFTRS_QQI(33,33,5, 
                                                        (((QData)((IData)(
                                                                          (((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_sra) 
                                                                            | (IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__instr_srai)) 
                                                                           & (vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1 
                                                                              >> 0x1fU)))) 
                                                          << 0x20U) 
                                                         | (QData)((IData)(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op1))), 
                                                        (0x1fU 
                                                         & vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__reg_op2))))),32);
    bufp->fullBit(oldp+269,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_eq));
    bufp->fullBit(oldp+270,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_ltu));
    bufp->fullBit(oldp+271,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__alu_lts));
    bufp->fullBit(oldp+272,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs_write));
    bufp->fullIData(oldp+273,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs_wrdata),32);
    bufp->fullIData(oldp+274,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs_rs1),32);
    bufp->fullIData(oldp+275,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__cpuregs_rs2),32);
    bufp->fullIData(oldp+276,((0xfffU & (vlSelf->tb_soc__DOT__dut__DOT__cpu_mem_addr 
                                         >> 2U))),32);
    bufp->fullBit(oldp+277,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_mem_ready));
    bufp->fullIData(oldp+278,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__dbg_mem_rdata),32);
    bufp->fullIData(oldp+279,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_rdata_word),32);
    bufp->fullBit(oldp+280,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_xfer));
    bufp->fullIData(oldp+281,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_rdata_latched_noshuffle),32);
    bufp->fullBit(oldp+282,(vlSelf->tb_soc__DOT__clk));
    bufp->fullBit(oldp+283,(vlSelf->tb_soc__DOT__resetn));
    bufp->fullBit(oldp+284,(vlSelf->tb_soc__DOT__sim_started));
    bufp->fullIData(oldp+285,(vlSelf->tb_soc__DOT__raw_periph_edges),32);
    bufp->fullIData(oldp+286,(vlSelf->tb_soc__DOT__gated_periph_edges),32);
    bufp->fullBit(oldp+287,(vlSelf->tb_soc__DOT__dut__DOT__clk_periph_raw));
    bufp->fullBit(oldp+288,(((IData)(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__ack_periph) 
                             | (IData)(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__req_cpu))));
    bufp->fullBit(oldp+289,(vlSelf->tb_soc__DOT__dut__DOT__clk_periph));
    bufp->fullBit(oldp+290,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__ack_periph));
    bufp->fullIData(oldp+291,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__PRDATA_from_periph),32);
    bufp->fullBit(oldp+292,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__req_periph_sync));
    bufp->fullBit(oldp+293,(vlSelf->tb_soc__DOT__dut__DOT__apb_cdc__DOT__sync_req__DOT__sync_ff1));
    bufp->fullBit(oldp+294,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_read));
    bufp->fullBit(oldp+295,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_la_write));
    bufp->fullBit(oldp+296,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__clear_prefetched_high_word));
    bufp->fullBit(oldp+297,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_done));
    bufp->fullBit(oldp+298,((1U & (~ (IData)(vlSelf->tb_soc__DOT__resetn)))));
    bufp->fullCData(oldp+299,(vlSelf->tb_soc__DOT__dut__DOT__periph_clk_div__DOT__counter),2);
    bufp->fullBit(oldp+300,(vlSelf->tb_soc__DOT__dut__DOT__periph_icg__DOT__en_latch));
    bufp->fullBit(oldp+301,(1U));
    bufp->fullCData(oldp+302,(0U),2);
    bufp->fullCData(oldp+303,(1U),2);
    bufp->fullCData(oldp+304,(2U),2);
    bufp->fullCData(oldp+305,(3U),2);
    bufp->fullBit(oldp+306,(0U));
    bufp->fullBit(oldp+307,(1U));
    bufp->fullIData(oldp+308,(0U),32);
    bufp->fullIData(oldp+309,(0xffffffffU),32);
    bufp->fullIData(oldp+310,(0x10U),32);
    bufp->fullBit(oldp+311,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_wr));
    bufp->fullIData(oldp+312,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_rd),32);
    bufp->fullBit(oldp+313,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_wait));
    bufp->fullBit(oldp+314,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_ready));
    bufp->fullIData(oldp+315,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__irq),32);
    bufp->fullIData(oldp+316,(0U),32);
    bufp->fullIData(oldp+317,(1U),32);
    bufp->fullIData(oldp+318,(2U),32);
    bufp->fullIData(oldp+319,(0x20U),32);
    bufp->fullIData(oldp+320,(5U),32);
    bufp->fullQData(oldp+321,(0x100000000ULL),36);
    bufp->fullQData(oldp+323,(0x200000000ULL),36);
    bufp->fullQData(oldp+325,(0x800000000ULL),36);
    bufp->fullIData(oldp+327,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__i),32);
    bufp->fullBit(oldp+328,(0U));
    bufp->fullSData(oldp+329,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__mem_16bit_buffer),16);
    bufp->fullCData(oldp+330,(0x80U),8);
    bufp->fullCData(oldp+331,(0x40U),8);
    bufp->fullCData(oldp+332,(0x20U),8);
    bufp->fullCData(oldp+333,(0x10U),8);
    bufp->fullCData(oldp+334,(8U),8);
    bufp->fullCData(oldp+335,(4U),8);
    bufp->fullCData(oldp+336,(2U),8);
    bufp->fullCData(oldp+337,(1U),8);
    bufp->fullCData(oldp+338,(vlSelf->tb_soc__DOT__dut__DOT__cpu__DOT__pcpi_timeout_counter),4);
    bufp->fullCData(oldp+339,(0U),5);
    bufp->fullIData(oldp+340,(0x4000U),32);
    bufp->fullIData(oldp+341,(0x1000U),32);
    bufp->fullIData(oldp+342,(0x20U),32);
}
